export const Nationality = [
    { country: "United Arab Emirates", nationality: "Emirati", Isocode: "AE" },
    { country: "India", nationality: "Indian", Isocode: "IN" },
    { country: "United States", nationality: "American", Isocode: "US" },
    { country: "United Kingdom", nationality: "British", Isocode: "GB" },
    { country: "Canada", nationality: "Canadian", Isocode: "CA" },
    { country: "Australia", nationality: "Australian", Isocode: "AU" },
    { country: "France", nationality: "French", Isocode: "FR" },
    { country: "Germany", nationality: "German", Isocode: "DE" },
    { country: "Italy", nationality: "Italian", Isocode: "IT" },
    { country: "Spain", nationality: "Spanish", Isocode: "ES" },
    { country: "Netherlands", nationality: "Dutch", Isocode: "NL" },
    { country: "Switzerland", nationality: "Swiss", Isocode: "CH" },
    { country: "Sweden", nationality: "Swedish", Isocode: "SE" },
    { country: "Norway", nationality: "Norwegian", Isocode: "NO" },
    { country: "Denmark", nationality: "Danish", Isocode: "DK" },
    { country: "Finland", nationality: "Finnish", Isocode: "FI" },
    { country: "Ireland", nationality: "Irish", Isocode: "IE" },
    { country: "Portugal", nationality: "Portuguese", Isocode: "PT" },
    { country: "Belgium", nationality: "Belgian", Isocode: "BE" },
    { country: "Austria", nationality: "Austrian", Isocode: "AT" },
    { country: "Poland", nationality: "Polish", Isocode: "PL" },
    { country: "Russia", nationality: "Russian", Isocode: "RU" },
    { country: "Ukraine", nationality: "Ukrainian", Isocode: "UA" },
    { country: "Turkey", nationality: "Turkish", Isocode: "TR" },
    { country: "Saudi Arabia", nationality: "Saudi", Isocode: "SA" },
    { country: "Qatar", nationality: "Qatari", Isocode: "QA" },
    { country: "Kuwait", nationality: "Kuwaiti", Isocode: "KW" },
    { country: "Oman", nationality: "Omani", Isocode: "OM" },
    { country: "Bahrain", nationality: "Bahraini", Isocode: "BH" },
    { country: "China", nationality: "Chinese", Isocode: "CN" },
    { country: "Japan", nationality: "Japanese", Isocode: "JP" },
    { country: "South Korea", nationality: "South Korean", Isocode: "KR" },
    { country: "North Korea", nationality: "North Korean", Isocode: "KP" },
    { country: "Thailand", nationality: "Thai", Isocode: "TH" },
    { country: "Vietnam", nationality: "Vietnamese", Isocode: "VN" },
    { country: "Indonesia", nationality: "Indonesian", Isocode: "ID" },
    { country: "Malaysia", nationality: "Malaysian", Isocode: "MY" },
    { country: "Singapore", nationality: "Singaporean", Isocode: "SG" },
    { country: "Philippines", nationality: "Filipino", Isocode: "PH" },
    { country: "Bangladesh", nationality: "Bangladeshi", Isocode: "BD" },
    { country: "Pakistan", nationality: "Pakistani", Isocode: "PK" },
    { country: "Sri Lanka", nationality: "Sri Lankan", Isocode: "LK" },
    { country: "Nepal", nationality: "Nepali", Isocode: "NP" },
    { country: "Egypt", nationality: "Egyptian", Isocode: "EG" },
    { country: "South Africa", nationality: "South African", Isocode: "ZA" },
    { country: "Nigeria", nationality: "Nigerian", Isocode: "NG" },
    { country: "Kenya", nationality: "Kenyan", Isocode: "KE" },
    { country: "Ethiopia", nationality: "Ethiopian", Isocode: "ET" },
    { country: "Morocco", nationality: "Moroccan", Isocode: "MA" },
    { country: "Argentina", nationality: "Argentine", Isocode: "AR" },
    { country: "Brazil", nationality: "Brazilian", Isocode: "BR" },
    { country: "Mexico", nationality: "Mexican", Isocode: "MX" },
    { country: "Chile", nationality: "Chilean", Isocode: "CL" },
    { country: "Colombia", nationality: "Colombian", Isocode: "CO" },
    { country: "Peru", nationality: "Peruvian", Isocode: "PE" },
  ];